HW34
pavlokhomiak/jv-shop pull request #14
Opened 2020-09-29 13:04 UTC by pavlokhomiak

2020-09-29 13:11 UTC, ilya449 commented
Well done!

2020-09-29 13:11 UTC, ilya449 approved these changes

2020-09-29 16:26 UTC, KseniiaMakarova requested changes

2020-09-29 16:26 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/UserDaoJdbcImpl.java
>              updateUserStatement.setLong(4, user.getId());
```suggestion
            updateUserStatement.setBytes(4, user.getSalt());
            updateUserStatement.setLong(5, user.getId());
```

2020-09-29 16:26 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/UserDaoJdbcImpl.java
> +                user.setSalt(salt);
let's move the repeated logic into the private method `getUserFromResultSet(ResultSet resultSet)`

2020-09-29 16:26 UTC, KseniiaMakarova commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
> +        byte[] salt = userFromDB.get().getSalt();
we are calling `get()` on Optional here
but we haven't checked yet if the value is present

2020-09-29 16:26 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +ADD COLUMN `salt` VARBINARY(256) NOT NULL AFTER `password`;
or we can modify CREATE statement

2020-09-29 17:52 UTC, KseniiaMakarova requested changes
everything is good
fix travis please

2020-09-30 06:52 UTC, KseniiaMakarova approved these changes

2020-09-30 06:56 UTC, merged